[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.13"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  DEBUG = "0"
  ALLOWED_HOSTS = "*.netlify.app"
  SITE_URL = "https://ewaw.netlify.app"
  CORS_ALLOWED_ORIGINS = "https://*.netlify.app"
  CSRF_TRUSTED_ORIGINS = "https://*.netlify.app"
  SECURE_SSL_REDIRECT = "true"
  SESSION_COOKIE_SECURE = "true"
  CSRF_COOKIE_SECURE = "true"
  DATABASE_URL = "sqlite:///db.sqlite3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"