[build]
  command = """
    cp .env.production .env &&
    python -m pip install -r requirements-netlify.txt &&
    python manage.py collectstatic --noinput &&
    mkdir -p staticfiles/data &&
    cp db.sqlite3 staticfiles/data/db.sqlite3
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11.0"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  DEBUG = "0"
  ALLOWED_HOSTS = "*.netlify.app"
  SITE_URL = "https://ewaw.netlify.app"
  CORS_ALLOWED_ORIGINS = "https://*.netlify.app"
  CSRF_TRUSTED_ORIGINS = "https://*.netlify.app"
  SECURE_SSL_REDIRECT = "true"
  SESSION_COOKIE_SECURE = "true"
  CSRF_COOKIE_SECURE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200