[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn crm.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[deploy.migrations]]
command = "python manage.py migrate"
