# Generated by Django 4.2.21 on 2025-06-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='وصف النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع العميل',
                'verbose_name_plural': 'أنواع العملاء',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='customer_type_code_idx'), models.Index(fields=['name'], name='customer_type_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة العملاء',
                'verbose_name_plural': 'فئات العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('blacklisted', 'قائمة سوداء')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.branch', verbose_name='الفرع')),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customertype', verbose_name='نوع العميل')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customercategory', verbose_name='فئة العميل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='cust_phone_idx'), models.Index(fields=['code'], name='cust_code_idx'), models.Index(fields=['name'], name='cust_name_idx'), models.Index(fields=['phone', 'phone2'], name='cust_phones_idx'), models.Index(fields=['email'], name='cust_email_idx'), models.Index(fields=['status'], name='cust_status_idx'), models.Index(fields=['customer_type'], name='cust_type_idx'), models.Index(fields=['created_at'], name='cust_created_idx'), models.Index(fields=['updated_at'], name='cust_updated_idx'), models.Index(fields=['branch', 'status', 'customer_type'], name='cust_br_st_type_idx'), models.Index(fields=['name', 'phone', 'email'], name='cust_search_idx'), models.Index(fields=['created_by', 'branch'], name='cust_creator_branch_idx'), models.Index(condition=models.Q(('status', 'active')), fields=['name', 'phone'], name='cust_active_idx')],
            },
        ),
    ]
