# Generated by Django 4.2.21 on 2025-06-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العقد')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعاينة')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعاينة المجدول')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('scheduled', 'مجدول'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('result', models.CharField(blank=True, choices=[('pass', 'ناجح'), ('fail', 'راسب'), ('pending', 'قيد الانتظار')], max_length=10, null=True, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='customers.customer', verbose_name='العميل')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='accounts.branch', verbose_name='الفرع')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'معاينة',
                'verbose_name_plural': 'المعاينات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100, verbose_name='المعيار')),
                ('rating', models.IntegerField(choices=[(1, 'ضعيف'), (2, 'مقبول'), (3, 'جيد'), (4, 'جيد جداً'), (5, 'ممتاز')], verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.inspection', verbose_name='المعاينة')),
            ],
            options={
                'verbose_name': 'تقييم المعاينة',
                'verbose_name_plural': 'تقييمات المعاينة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection'], name='inspection_eval_insp_idx'), models.Index(fields=['criteria'], name='inspection_eval_criteria_idx'), models.Index(fields=['rating'], name='inspection_eval_rating_idx'), models.Index(fields=['created_by'], name='inspection_eval_creator_idx'), models.Index(fields=['created_at'], name='inspection_eval_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['contract_number'], name='inspection_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['customer'], name='inspection_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['branch'], name='inspection_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector'], name='inspection_inspector_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspection_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['result'], name='inspection_result_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['request_date'], name='inspection_req_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['scheduled_date'], name='inspection_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['order'], name='inspection_order_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['created_at'], name='inspection_created_idx'),
        ),
    ]
