# Generated by Django 4.2.21 on 2025-06-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التركيب المجدول')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التركيب الفعلي')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء التركيب الفعلي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('scheduled', 'مجدول'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, 'ضعيف'), (2, 'مقبول'), (3, 'جيد'), (4, 'جيد جداً'), (5, 'ممتاز')], null=True, verbose_name='تقييم الجودة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installations', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='inspections.inspection', verbose_name='المعاينة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تركيب',
                'verbose_name_plural': 'التركيبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفريق')),
                ('members', models.ManyToManyField(blank=True, related_name='installation_teams', to=settings.AUTH_USER_MODEL, verbose_name='أعضاء الفريق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فريق التركيب',
                'verbose_name_plural': 'فرق التركيب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100, verbose_name='المعيار')),
                ('result', models.CharField(choices=[('pass', 'ناجح'), ('fail', 'راسب')], max_length=10, verbose_name='النتيجة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='installations/quality/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفحص')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to=settings.AUTH_USER_MODEL, verbose_name='تم الفحص بواسطة')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='installations.installation', verbose_name='عملية التركيب')),
            ],
            options={
                'verbose_name': 'فحص جودة',
                'verbose_name_plural': 'فحوصات الجودة',
                'ordering': ['-created_at'],
                'unique_together': {('installation', 'criteria')},
            },
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['order'], name='install_order_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['inspection'], name='install_inspection_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['team'], name='install_team_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['status'], name='install_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['scheduled_date'], name='install_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['created_at'], name='install_created_idx'),
        ),
    ]
